"add title & description"
anurag629/BotaniScan pull request #15
Opened 2023-09-14 08:14 UTC by Subrat29

Add title and description in about.mdx.
can i add know more(link) or problem id in it??

2023-09-14 08:31 UTC, anurag629 requested changes
Also, change this description according to statement

![image](https://github.com/anurag629/BotaniScan/assets/78868769/9014663b-edc0-4ddf-a59f-487ad41cfede)

2023-09-14 08:31 UTC, anurag629 commented on app/aboutproject/about.mdx
> +### Identification of Different Medicinal Plants/Raw materials through Image Processing Using Machine Learning Algorithms
Leave a line between lines first and second. Make the statement in `**Identification of Different...**` 


Look through [MDX Guide](https://kabartolo.github.io/chicago-docs-demo/docs/mdx-guide/writing/)

2023-09-14 08:31 UTC, anurag629 commented on app/aboutproject/about.mdx
> +* India, with a rich heritage of floral diversity, is well-known for its medicinal plant wealth, but their identification is one of the major burning issues in Ayurvedic Pharmaceutics. Several crude
Same leave a line between line 4 and 5

2023-09-14 10:04 UTC, Subrat29 commented on app/aboutproject/about.mdx
> +### Identification of Different Medicinal Plants/Raw materials through Image Processing Using Machine Learning Algorithms
ok done

2023-09-14 10:04 UTC, Subrat29 commented on app/aboutproject/about.mdx
> +* India, with a rich heritage of floral diversity, is well-known for its medicinal plant wealth, but their identification is one of the major burning issues in Ayurvedic Pharmaceutics. Several crude
ok done

2023-09-15 12:29 UTC, anurag629 approved these changes

2023-09-15 12:29 UTC, merged